par(mfrow=c(2,2))
plot(data3$t,data3$Global_active_power,type="l",xlab="",ylab="Global Active Power")
plot(data3$t,data3$Voltage,type="l",xlab="datetime",ylab="Voltage")
plot(data3$t,data3$Sub_metering_1,type="s",xlab="",ylab="Energy sub metering")
lines(data3$t,data3$Sub_metering_2,col="red")
lines(data3$t,data3$Sub_metering_3,col="blue")
legend("topright",legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black","red","blue"),lty=1, cex=0.7,y.intersp=0.3,bty="n")
plot(data3$t,data3$Global_reactive_power,type="l",xlab="datetime",ylab="Global_reactive_power")
dev.copy(png, file="plot4.png")
dev.off()